### ISSUE TITLE
GA_MEASUREMENT_ID=YOUR MEASUREMENT ID ???

### ISSUE THREAD

**Issue by plazma1745** [flotiq/flotiq-gatsby-event-1#14]
Click "Preview" for a nicer view!

For support, help, questions, requests and ideas use https://discord.gg/FwXcHnX

Alternatively, check out these resources below. Thanks!

- [Discord](https://discord.gg/FwXcHnX)
- [Gatsby API reference](https://docs.ghost.org/api/gatsby/)
- [Content API Docs](https://flotiq.com/docs/panel/)
- [Gatsby.js](https://www.gatsbyjs.org)
- [GraphQL](https://graphql.org/)

**Comment by trzcina** [comment]
Thanks for the reporting. 
"YOUR MEASUREMENT ID" means Google Analytics Measurement ID. 
Here you can check how to find this variable: 
https://flotiq.com/blog/how-to-update-your-gatsby-site-to-google-analytics-v4-migration-guide

You can also leave it empty or remove the gtag plugin used here:
https://github.com/flotiq/flotiq-gatsby-event-1/blob/master/gatsby-config.js#L22

We will rename the placeholder value to be more clear.
